# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/ossi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ossi)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,224c3d099cd462e550a322bec96077b7468e7c2c)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,9e229de08f417f8472aeef0c5b5eec140292f1b2)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,a11912ee67f065d94625b26ccba260788622eb60)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,b3035b707fa5037f0cfe496af49a009ed20ac89c)
$(call add-radio-file-sha1-checked,radio/cdt_engineering.img,e117a4fd0e8710102e980d3e83f37c72b8cf0596)
$(call add-radio-file-sha1-checked,radio/gz.img,980b0f3eded68dfeb8cee38727d9edb911cce944)
$(call add-radio-file-sha1-checked,radio/lk.img,7b075d1e5a15e079a34cce3d352c7581baeaa33b)
$(call add-radio-file-sha1-checked,radio/logo.bin,2fce7bb291e6511b83f3f3824a573bde2573675d)
$(call add-radio-file-sha1-checked,radio/md1img.img,b4362e81a3f9de75c98fe7855eb8808767dcd436)
$(call add-radio-file-sha1-checked,radio/preloader_ufs.img,c39637205f4a216f1f545154555909803eba4c9b)
$(call add-radio-file-sha1-checked,radio/scp.img,b2e78c1dc79f3d837126c3acd0f7d9f8836b23a0)
$(call add-radio-file-sha1-checked,radio/spmfw.img,02c0836759faefa2b54e2b575ab4a02b04429844)
$(call add-radio-file-sha1-checked,radio/sspm.img,a39253a58203f685063e8d2d9525faf2c424e74e)
$(call add-radio-file-sha1-checked,radio/tee.img,151beb5e2837233c30d70b2a39b1918231ae2a48)

endif
